"""Site content. Everything here comes from material already published on altherix.in
(case studies, team, services, careers). Do not add clients, figures or certifications
that are not supported by real work."""

SITE = "https://altherix.in"
EMAIL = "contact@altherix.in"
PHONE_DISPLAY = "+91 81529 23515"
PHONE_TEL = "+918152923515"
LINKEDIN = "https://www.linkedin.com/company/altherix"
ADDRESS = ["1247 N1, LN Gardens, Stanley Park", "Ottupattarai, Coonoor", "Nilgiris, Tamil Nadu 643105"]

# ────────────────────────────────────────────────────────────────────────────
# CASE STUDIES
# ────────────────────────────────────────────────────────────────────────────
CASES = [
  dict(
    slug="church-management-system",
    featured=True,
    category="Non-profit · Enterprise platform",
    industry="Enterprise / Nonprofit",
    title="Church Management System",
    client="The Church of Pentecost",
    oneliner="A congregation management platform replacing spreadsheets and paper registers with one record of every member, group, event and attendance.",
    summary="For The Church of Pentecost, Altherix designed, built and deployed a full congregation management platform. It replaced spreadsheets and paper registers with a single record of every member, group, event and attendance across the organisation's assemblies, and runs in production on Azure.",
    problem="Member records, groups, events and attendance lived in spreadsheets and paper registers spread across assemblies.",
    solution="One platform for the member lifecycle, recurring events, real-time check-in, inter-assembly transfers and leadership analytics.",
    challenge=[
      "Congregation data was held in spreadsheets and paper registers, so there was no single, reliable record of members, groups, events or attendance across assemblies.",
      "The platform had to handle the real shape of church life: households and home cells, members moving between assemblies, services that recur every week with exceptions, and visitors who arrive without a record.",
    ],
    approach=[
      ("Model the domain first", "Member lifecycle — education and career history, salvation and baptism status, household and home-cell membership — modelled as first-class data rather than free text."),
      ("Automate the paperwork", "Inter-assembly transfers run as a request workflow that generates the transfer letter automatically."),
      ("Treat recurrence properly", "Recurring services are expanded into individual occurrences by a scheduled background job, so each occurrence can carry its own exceptions."),
      ("Migrate, don't retype", "Excel import and export so existing registers could be brought across in bulk."),
    ],
    architecture=[
      ("Experience", "React 18 and TypeScript front end with MUI and Redux Toolkit"),
      ("Application", "ASP.NET Core on .NET 9 — membership, events, attendance, transfers and reporting modules"),
      ("Real-time & jobs", "SignalR for live check-in over WebSockets; Hangfire for scheduled recurrence expansion"),
      ("Data", "SQL Server through Entity Framework Core"),
      ("Cloud", "Azure (UK South), released through a gated pipeline"),
    ],
    engineering=[
      ("Live check-in", "real-time attendance capture over WebSockets, including visitors and anonymous attendees"),
      ("Background processing", "recurring events expanded into occurrences by a scheduled job, with per-occurrence exceptions"),
      ("Bulk data", "Excel import and export for migrating existing registers"),
      ("Reporting", "dashboards and generated PDF reports for leadership"),
      ("Controls", "role-based access and audit logging throughout"),
    ],
    tech=[".NET 9", "ASP.NET Core", "EF Core", "SQL Server", "SignalR", "Hangfire", "React 18", "TypeScript", "MUI", "Redux Toolkit", "Azure"],
    metrics=[("80+", "API modules"), ("2", "Connected apps"), ("Live", "In production on Azure")],
    headline=("80+", "API modules in production"),
    impact="Congregation operations moved from paper and spreadsheets onto one system of record, live in production and delivered as part of a multi-year engagement that also produced the Missions Office Enterprise System.",
    related_service="software-engineering",
  ),
  dict(
    slug="missions-office-enterprise-system",
    featured=True,
    category="Non-profit · Enterprise reporting",
    industry="Enterprise / Nonprofit",
    title="Missions Office Enterprise System",
    client="The Church of Pentecost",
    oneliner="Global statistical reporting consolidated across a seven-tier organisational hierarchy, with drill-down dashboards and audited exports.",
    summary="A reporting and analytics system for the Church of Pentecost's global Missions Office. It consolidates half-year and end-year statistical returns submitted from every level of a seven-tier hierarchy, from the Global Office down to a single local assembly.",
    problem="Half-year and end-year statistical returns had to be consolidated across seven organisational levels, with each administrator seeing only their own branch.",
    solution="Drill-down statistics dashboards, access scoped at query level, a Vision 2028 scorecard and exports stamped with their provenance.",
    challenge=[
      "Statistical returns arrive from every level of a seven-tier hierarchy: Global Office → Regional Missions Office → Regional Committee → Nation → Area → District → Local Assembly.",
      "Leadership needed to read the same figures from the top of the organisation down to one assembly, while every administrator must only ever see the branch they are responsible for.",
    ],
    approach=[
      ("Scope at the query, not the screen", "Access is enforced at query level, so an administrator can only ever retrieve their own branch of the hierarchy."),
      ("One model, many altitudes", "Membership, evangelism, attendance, ministry and estates dashboards, each with drill-down from global to a single assembly."),
      ("Measure against the plan", "A configurable Vision 2028 scorecard with indicators, targets and pace-adjusted progress tracking."),
      ("Know what's missing", "Data-completeness tracking shows which assemblies have submitted for a period and lists those outstanding."),
    ],
    architecture=[
      ("Experience", "Server-rendered views with Alpine.js and Chart.js dashboards"),
      ("Application", "Laravel 12 on PHP 8.2 — returns, hierarchy, scorecard and export modules"),
      ("Access", "Hierarchy-scoped authorisation applied at query level"),
      ("Data", "MySQL"),
      ("Cloud", "Azure App Service, released through Azure DevOps pipelines"),
    ],
    engineering=[
      ("Seven-level hierarchy", "Global Office → Regional Missions Office → Regional Committee → Nation → Area → District → Local Assembly"),
      ("Statistics dashboards", "membership, evangelism, attendance, ministry and estates, each with drill-down"),
      ("Scoped access", "enforced at query level"),
      ("Vision 2028 scorecard", "configurable indicators and targets with pace-adjusted progress"),
      ("Exports & provenance", "CSV and PDF exports stamped with scope, period and generation trail"),
      ("Data completeness", "tracks which assemblies have submitted and which are outstanding"),
    ],
    tech=["Laravel 12", "PHP 8.2", "MySQL", "Alpine.js", "Chart.js", "dompdf", "Azure App Service", "Azure DevOps"],
    metrics=[("7", "Hierarchy levels"), ("6", "Dashboard modules"), ("Live", "In production on Azure")],
    headline=("7", "Organisational levels, one reporting system"),
    impact="Statistical reporting for a global organisation now runs through one governed system, with figures that can be traced from the Global Office down to a single assembly and exports that record exactly what they contain.",
    related_service="enterprise-integration",
  ),
  dict(
    slug="erp-inventory-module",
    category="Manufacturing · ERP",
    industry="Manufacturing",
    title="ERP Inventory Management Module",
    client=None,
    oneliner="Inventory management inside the ERP — barcode scanning, real-time stock updates and automated reorder alerts.",
    summary="A custom inventory management module for a mid-sized manufacturer's ERP, adding barcode scanning, real-time stock updates and automated reorder alerts.",
    problem="Stock movements for a mid-sized manufacturer were handled with a large amount of manual work.",
    solution="An ERP inventory module with barcode scanning, real-time stock updates and automated reorder alerts.",
    challenge=["A mid-sized manufacturer needed its inventory handled inside the ERP, with stock levels kept current as goods move and reorders raised without relying on manual checks."],
    approach=[
      ("Capture at the source", "Barcode scanning records stock movements as they happen."),
      ("Keep stock current", "Stock levels update in real time as movements are recorded."),
      ("Automate the reorder", "Reorder alerts are raised automatically when stock needs replenishing."),
    ],
    architecture=[
      ("Capture", "Barcode scanning"),
      ("Application", "Java Spring Boot services exposing REST APIs"),
      ("Data", "MySQL"),
    ],
    engineering=[("Barcode scanning", "stock movements captured at the point of handling"), ("Real-time stock", "levels updated as movements are recorded"), ("Reorder alerts", "raised automatically")],
    tech=["Java", "Spring Boot", "MySQL", "REST API"],
    metrics=[("85%", "Less manual work"), ("5K+", "SKUs managed")],
    headline=("85%", "Less manual work"),
    impact="Manual inventory work fell by 85% across more than 5,000 SKUs.",
    related_service="modernization",
  ),
  dict(
    slug="payment-gateway-integration",
    category="E-commerce · Payments",
    industry="Financial Services",
    title="Multi-Gateway Payment Integration",
    client=None,
    oneliner="Razorpay, PayU and Paytm behind one integration, with UPI, wallets, EMI, an admin dashboard and automated reconciliation.",
    summary="A multi-gateway payment integration covering Razorpay, PayU and Paytm, supporting UPI, wallets and EMI, with an admin dashboard and automated reconciliation reports.",
    problem="An e-commerce business needed more payment options at checkout and a reliable way to reconcile payments across providers.",
    solution="Three gateways behind one integration, UPI, wallets and EMI at checkout, an admin dashboard and automated reconciliation reports.",
    challenge=["An e-commerce business needed to offer customers more ways to pay and reconcile payments across several providers without doing it by hand."],
    approach=[
      ("Integrate once, route many", "Razorpay, PayU and Paytm integrated behind a single payment layer."),
      ("Offer the methods customers use", "UPI, wallets and EMI supported at checkout."),
      ("Reconcile automatically", "Reconciliation reports generated automatically, with an admin dashboard for operations."),
    ],
    architecture=[
      ("Experience", "React checkout and admin dashboard"),
      ("Application", "Node.js payment services integrating Razorpay, PayU and Paytm"),
      ("Data", "MongoDB"),
    ],
    engineering=[("Multi-gateway", "Razorpay, PayU and Paytm"), ("Payment methods", "UPI, wallets and EMI"), ("Operations", "admin dashboard"), ("Finance", "automated reconciliation reports")],
    tech=["Node.js", "React", "MongoDB", "Razorpay", "PayU", "Paytm", "UPI"],
    metrics=[("35%", "Higher conversions"), ("2K+", "Daily orders")],
    headline=("35%", "Higher conversions"),
    impact="Conversions rose by 35%, with the integration handling more than 2,000 orders a day.",
    related_service="enterprise-integration",
  ),
  dict(
    slug="accounting-software-integration",
    category="Financial services · Integration",
    industry="Financial Services",
    title="Accounting Software Integration",
    client=None,
    oneliner="A REST API bridge between billing and Tally / Zoho Books, with automated invoicing, GST preparation and payment reconciliation.",
    summary="A REST API bridge between a billing system and Tally and Zoho Books, automating invoice generation, GST preparation and payment reconciliation.",
    problem="Invoices, GST preparation and payment reconciliation were being carried between billing and accounting by hand.",
    solution="A REST API bridge to Tally and Zoho Books that generates invoices, prepares GST data and reconciles payments automatically.",
    challenge=["Billing and accounting were separate systems, so invoices, GST preparation and payment reconciliation had to be carried across manually."],
    approach=[
      ("Bridge, don't replace", "A REST API bridge connects the existing billing system to Tally and Zoho Books."),
      ("Automate the repetitive", "Invoice generation and GST preparation happen automatically."),
      ("Close the loop", "Payments are reconciled automatically against the accounting records."),
    ],
    architecture=[
      ("Source", "Billing system"),
      ("Integration", "Python Django REST API bridge"),
      ("Data", "PostgreSQL"),
      ("Targets", "Tally and Zoho Books"),
    ],
    engineering=[("Invoicing", "automated invoice generation"), ("Tax", "GST preparation"), ("Reconciliation", "automated payment reconciliation")],
    tech=["Python", "Django", "PostgreSQL", "REST API", "Tally", "Zoho Books"],
    metrics=[("90%", "Time saved"), ("100%", "Accuracy")],
    headline=("90%", "Time saved"),
    impact="The integration saved 90% of the time previously spent and delivered 100% accuracy.",
    related_service="enterprise-integration",
  ),
  dict(
    slug="clinic-management-enhancement",
    category="Healthcare · Platform enhancement",
    industry="Healthcare",
    title="Clinic Management Enhancement",
    client=None,
    oneliner="Appointment booking, prescriptions, SMS and email reminders and telemedicine across four clinics.",
    summary="Enhancements to a clinic management system across four clinics serving more than 3,000 patients a month: appointment booking, prescription management, SMS and email reminders, and telemedicine.",
    problem="Four clinics serving more than 3,000 patients a month needed better booking, prescriptions and a way to reduce missed appointments.",
    solution="Appointment booking, prescription management, SMS and email reminders and telemedicine added to the existing system.",
    challenge=["Four clinics serving more than 3,000 patients a month needed booking, prescriptions and patient communication improved within their existing system, and missed appointments reduced."],
    approach=[
      ("Enhance the existing system", "New capability added to the clinic system already in use."),
      ("Remind, automatically", "SMS and email reminders sent ahead of appointments."),
      ("Extend care", "Telemedicine features alongside booking and prescription management."),
    ],
    architecture=[
      ("Experience", "Angular front end"),
      ("Application", "Node.js services"),
      ("Messaging", "Twilio for SMS; email reminders"),
    ],
    engineering=[("Booking", "appointment booking"), ("Prescriptions", "prescription management"), ("Reminders", "SMS and email"), ("Telemedicine", "remote consultation features")],
    tech=["Angular", "Node.js", "Twilio"],
    metrics=[("70%", "Fewer no-shows"), ("3K+", "Patients per month"), ("4", "Clinics")],
    headline=("70%", "Fewer no-shows"),
    impact="No-shows fell by 70% across four clinics serving more than 3,000 patients a month.",
    related_service="modernization",
  ),
  dict(
    slug="learning-platform-features",
    category="Education · Product engineering",
    industry="Education",
    title="Learning Platform Features",
    client=None,
    oneliner="Video delivery, quizzes, progress tracking, certificates, Zoom and Razorpay for an ed-tech startup.",
    summary="Feature development for an ed-tech startup's learning platform: video delivery, quizzes, progress tracking, certificate generation, Zoom integration and Razorpay payments.",
    problem="An ed-tech startup needed its learning platform extended with the features a growing student base expects.",
    solution="Video delivery, quizzes, progress tracking, certificate generation, Zoom integration and Razorpay payments.",
    challenge=["An ed-tech startup needed its platform extended from content delivery into a complete learning experience, including assessment, progress, certification, live classes and payments."],
    approach=[
      ("Learn", "Video delivery with content stored on AWS S3."),
      ("Assess", "Quizzes and progress tracking."),
      ("Recognise", "Automatic certificate generation."),
      ("Connect and pay", "Zoom integration for live sessions and Razorpay for payments."),
    ],
    architecture=[
      ("Experience", "React front end"),
      ("Application", "Python Django"),
      ("Media", "AWS S3"),
      ("Integrations", "Zoom and Razorpay"),
    ],
    engineering=[("Video", "delivery from AWS S3"), ("Assessment", "quizzes and progress tracking"), ("Certificates", "automatic generation"), ("Integrations", "Zoom and Razorpay")],
    tech=["React", "Python", "Django", "AWS S3", "Zoom", "Razorpay"],
    metrics=[("8K+", "Active students"), ("92%", "Completion rate")],
    headline=("8K+", "Active students"),
    impact="The platform serves more than 8,000 active students with a 92% completion rate.",
    related_service="software-engineering",
  ),
  dict(
    slug="delivery-management-system",
    category="Logistics · Mobile & platform",
    industry="Logistics",
    title="Delivery Management System",
    client=None,
    oneliner="Real-time tracking, a delivery agent app, route optimisation and customer SMS, integrated with Google Maps.",
    summary="A delivery management system with real-time tracking, a delivery agent mobile app, route optimisation and customer SMS notifications, integrated with Google Maps.",
    problem="Deliveries needed to be tracked in real time, routed efficiently and communicated to customers.",
    solution="A delivery agent mobile app, real-time tracking, route optimisation and SMS notifications on Google Maps.",
    challenge=["A delivery operation needed real-time visibility of its agents, better routes and automatic updates to customers."],
    approach=[
      ("Put the tool in the agent's hand", "A React Native mobile app for delivery agents."),
      ("See it live", "Real-time tracking integrated with Google Maps."),
      ("Route better", "Route optimisation for daily delivery runs."),
      ("Tell the customer", "SMS notifications at the right moments."),
    ],
    architecture=[
      ("Mobile", "React Native agent app"),
      ("Application", "Node.js services"),
      ("Mapping", "Google Maps for tracking and routing"),
      ("Messaging", "Customer SMS notifications"),
    ],
    engineering=[("Tracking", "real-time"), ("Agent app", "React Native"), ("Routing", "route optimisation"), ("Notifications", "customer SMS")],
    tech=["React Native", "Node.js", "Google Maps", "SMS"],
    metrics=[("40%", "Faster deliveries"), ("200+", "Daily deliveries")],
    headline=("40%", "Faster deliveries"),
    impact="Deliveries became 40% faster across more than 200 deliveries a day.",
    related_service="software-engineering",
  ),
]
CASE = {c["slug"]: c for c in CASES}

# ────────────────────────────────────────────────────────────────────────────
# SERVICES
# ────────────────────────────────────────────────────────────────────────────
SERVICES = [
  dict(
    slug="software-engineering", n="01", name="Software Engineering",
    short="Full-stack applications and enterprise platforms, designed, built and taken into production by the engineers who scoped them.",
    list=["Full-stack applications", "Enterprise platforms", "APIs & microservices", "Product engineering"],
    tech=[".NET", "Java / Spring Boot", "Laravel", "Node.js", "Python / Django", "React", "Angular", "React Native"],
    h1="Software that goes into production and <em>stays there.</em>",
    lede="We design and build full-stack applications and enterprise platforms — the data model, the API, the front end and the deployment — and we stay with them after launch.",
    problem=[
      "Most software projects don't fail at the code. They fail at the edges: requirements that were never pinned down, a data model that can't carry the real domain, a front end nobody was consulted on, and a deployment treated as someone else's job.",
      "We keep those edges inside one team. The engineers who talk to you are the engineers who build it.",
    ],
    approach=[
      ("Scope with the people who build", "Ambiguous requirements are turned into a shippable scope by the engineers who will deliver it."),
      ("Model the domain properly", "Relational schemas designed around how your organisation actually works, so the data stays trustworthy as it grows."),
      ("Build across the stack", "APIs, background processing, real-time features and front ends designed as one system."),
      ("Own the release", "CI/CD, cloud hosting and production support are part of the work, not an afterthought."),
    ],
    caps=[
      ("Full-stack applications", "Web applications with a considered component architecture, from API to interface."),
      ("Enterprise platforms", "Multi-module systems with role-based access, audit trails and reporting — built for organisations that depend on them daily."),
      ("APIs & microservices", "REST APIs and service boundaries that other systems and teams can rely on."),
      ("Product engineering", "New features and modules for existing products — design, build, test and deploy."),
      ("Real-time & background work", "WebSocket features (SignalR) and scheduled jobs (Hangfire) where the problem needs them."),
      ("Mobile", "React Native apps for field teams, integrated with the platform behind them."),
    ],
    cases=["church-management-system", "learning-platform-features", "delivery-management-system", "clinic-management-enhancement"],
  ),
  dict(
    slug="modernization", n="02", name="Modernization",
    short="Improve before you replace. Upgrade stacks, refactor architecture and move to the cloud without losing the knowledge built into your systems.",
    list=["Legacy modernization", "Architecture refactoring", "Cloud migration", "Performance engineering"],
    tech=["Azure", "AWS", ".NET", "Spring Boot", "Laravel", "SQL Server", "MySQL", "PostgreSQL"],
    h1="Most companies don't need <em>another rewrite.</em>",
    lede="Existing systems hold years of business rules that nobody wrote down. We modernise them deliberately — upgrading, refactoring and migrating in steps — instead of throwing them away.",
    problem=[
      "A full rewrite looks clean on a slide and is usually the riskiest option on the table. It discards knowledge encoded in the old system, stalls new features for months and often recreates the same problems on a newer stack.",
      "Modernisation should reduce risk, not move it. We start with what already works and change what doesn't.",
    ],
    approach=[
      ("Understand what's there", "Map the existing system, its data and the business rules it quietly enforces."),
      ("Change in steps", "Stack upgrades and architecture refactoring delivered incrementally, without stopping operations."),
      ("Move when it pays", "Cloud migration planned around cost, risk and what the workload actually needs."),
      ("Make it fast", "Profile first, then fix: query tuning, caching and scaling where the evidence points."),
    ],
    caps=[
      ("Technology stack upgrades", "Bring frameworks, runtimes and dependencies up to date without a rewrite."),
      ("Architecture refactoring", "Untangle modules, introduce clear service boundaries and make the codebase safe to change."),
      ("Cloud migration", "Move from on-premise or shared hosting into the cloud, primarily Azure."),
      ("Performance engineering", "Database query optimisation, caching and CDN strategy, load balancing and scaling."),
      ("Paper and spreadsheet replacement", "Turn registers and spreadsheets into a governed system of record, with bulk import of existing data."),
      ("Enhancement of live systems", "New modules added to systems already in use, such as booking, reminders and inventory."),
    ],
    cases=["church-management-system", "clinic-management-enhancement", "erp-inventory-module", "missions-office-enterprise-system"],
  ),
  dict(
    slug="ai-automation", n="03", name="AI & Automation",
    short="Automation that removes real manual work — and AI where it genuinely helps, built with the same engineering discipline as everything else.",
    list=["AI integrations", "AI agents", "Intelligent workflows", "Process automation"],
    tech=["Python", "LLM APIs", "Workflow orchestration", "REST integrations", "Background jobs", "Human review steps"],
    h1="AI that works <em>in production.</em>",
    lede="AI doesn't replace good engineering. It depends on it. We connect AI to the systems and data you already have, and we're just as ready to tell you when conventional automation is the better answer.",
    problem=[
      "AI doesn't fix broken processes. Most failed AI projects are integration and data problems in disguise: the model works in a demo, but it can't reach the right data, can't be trusted without review, and nobody owns it once it's live.",
      "We treat AI as one component in a production system — with access controls, logging, human oversight and a clear definition of what \"working\" means.",
    ],
    approach=[
      ("Start with the process", "Find where the manual effort actually is. Often the right answer is conventional automation."),
      ("Connect to real data", "AI is only as useful as the business data and systems it can safely reach."),
      ("Keep a human in the loop", "Multi-step automation with review points where the stakes justify them."),
      ("Run it like software", "Deployed, logged, access-controlled and monitored like everything else we ship."),
    ],
    caps=[
      ("AI integration", "Connect AI capabilities to existing business applications."),
      ("AI agents", "Automate multi-step workflows with appropriate human oversight."),
      ("Intelligent automation", "Turn repetitive operational processes into adaptive workflows."),
      ("Enterprise AI", "Build secure, governed AI experiences around business data."),
      ("Process automation", "Invoicing, reconciliation, reminders, alerts and scheduled jobs that remove repetitive work."),
      ("Automation you can audit", "Logging, audit trails and scoped access built in from the start."),
    ],
    cases=["accounting-software-integration", "erp-inventory-module", "clinic-management-enhancement", "missions-office-enterprise-system"],
    cases_title="Automation already in production",
    cases_note="These engagements are automation work — invoicing, reconciliation, alerts, reminders and data-completeness tracking — rather than AI. They show the kind of manual effort we look to remove first.",
  ),
  dict(
    slug="enterprise-integration", n="04", name="Enterprise Integration",
    short="Connect business systems so data moves once, correctly — SAP and ERP, accounting, payments and third-party APIs.",
    list=["SAP and enterprise integrations", "Business systems", "Data integration", "Third-party APIs"],
    tech=["REST", "SAP", "Tally", "Zoho Books", "Razorpay", "PayU", "Paytm", "Twilio", "Google Maps", "Zoom"],
    h1="Systems that talk to each other, <em>correctly.</em>",
    lede="Most organisations run on several systems that were never designed to work together. We build the integrations that let data move once, accurately, without someone re-keying it.",
    problem=[
      "When systems don't connect, people become the integration layer — exporting, re-keying and reconciling by hand. It's slow, it's error-prone, and it hides the real state of the business.",
      "We build integrations as production software: versioned APIs, reconciliation, error handling and a clear record of what moved and when.",
    ],
    approach=[
      ("Map the data flow", "Understand where each piece of data originates, who owns it and where it needs to be."),
      ("Build a bridge, not a tangle", "Clean API layers between systems instead of point-to-point scripts."),
      ("Reconcile automatically", "Every integration that moves money or records gets a way to prove it balanced."),
      ("Run it in the cloud", "Pipelines, environments, monitoring and alerting so failures are seen before users see them."),
    ],
    caps=[
      ("SAP and ERP integration", "Connect enterprise and ERP systems to the applications around them."),
      ("Accounting & finance", "Billing-to-accounting bridges with automated invoicing, GST preparation and reconciliation."),
      ("Payments", "Multi-gateway integrations with UPI, wallets, EMI and reconciliation reporting."),
      ("Third-party APIs", "Messaging, mapping, video and other services integrated reliably."),
      ("Data integration & reporting", "Consolidating data across organisational levels into governed dashboards and exports."),
      ("RESTful & GraphQL APIs", "API design for systems that other teams and partners depend on."),
    ],
    cloud=dict(
      title="Cloud & DevOps",
      text="Integration only works if it keeps working. We build and maintain CI/CD pipelines across Azure DevOps and GitHub Actions, provision and harden cloud infrastructure — primarily on Azure — and set up the monitoring, logging and alerting that tells us something is wrong before you do.",
      list=["CI/CD with Azure DevOps and GitHub Actions", "Azure App Service, SQL and Blob Storage", "Gated release pipelines", "Monitoring, logging and alerting", "Secrets, backups and access control", "Containers and infrastructure-as-code"],
    ),
    cases=["accounting-software-integration", "payment-gateway-integration", "missions-office-enterprise-system", "delivery-management-system"],
  ),
]
SERVICE = {s["slug"]: s for s in SERVICES}

# ────────────────────────────────────────────────────────────────────────────
# INDUSTRIES (each backed by real case studies)
# ────────────────────────────────────────────────────────────────────────────
INDUSTRIES = [
  ("Manufacturing", "Inventory inside the ERP: barcode scanning, real-time stock and automated reorder alerts across 5,000+ SKUs.", ["erp-inventory-module"]),
  ("Financial Services", "Billing-to-accounting bridges for Tally and Zoho Books with GST preparation, and multi-gateway payments with automated reconciliation.", ["accounting-software-integration", "payment-gateway-integration"]),
  ("Healthcare", "Booking, prescriptions, reminders and telemedicine across four clinics and 3,000+ patients a month.", ["clinic-management-enhancement"]),
  ("Education", "Video learning, assessment, certification, live classes and payments for 8,000+ active students.", ["learning-platform-features"]),
  ("Logistics", "Real-time tracking, an agent mobile app, route optimisation and customer SMS for 200+ daily deliveries.", ["delivery-management-system"]),
  ("Enterprise / Nonprofit", "Two production platforms for a global organisation — congregation management and statistical reporting across seven levels.", ["church-management-system", "missions-office-enterprise-system"]),
]

# ────────────────────────────────────────────────────────────────────────────
# TEAM
# ────────────────────────────────────────────────────────────────────────────
TEAM = [
  ("Ganesh S", "Director & Founder", "GS", ["Enterprise architecture", "SAP", "Cloud architecture"]),
  ("Priscilla Mathews", "Chief Financial Officer", "PM", ["Project economics", "Contracts", "Risk management"]),
  ("Muralidharan R", "Senior Software Engineer", "MR", ["Java / Spring Boot", "React / Angular", "Microservices"]),
  ("Jessy Varghese", "Software Engineer", "JV", ["Node.js / Python", "AWS / Azure", "Database design"]),
  ("Cyril Johnson", "Technical Advisor", "CJ", ["Architecture", "Technology strategy", "Emerging technologies"]),
  ("Rohan Raj", "Software Engineer", "RR", ["REST APIs", "Java / Python", "PostgreSQL / MySQL"]),
]
